### ISSUE TITLE
A failure in the cleanup phase should not make the entire plugin fail

### ISSUE THREAD

**Issue by tosky** [rhos-infra/horizon-infrared-plugin#15]
Right now, if a cleanup operation failes (like "Remove internal network", but I guess the same applies to other "Remove <foo>" tasks), then the entire module fails. The failure may be reported but probably should not affect the result of the plugin, whose purpose is to run the selenium tests.

**Comment by tosky** [comment]
@ashu-011 ^^

**Comment by ashu-011** [comment]
fixed in this PR : https://github.com/rhos-infra/horizon-infrared-plugin/pull/16
